data:
  parquet_dir: data/processed/parquet

targets:
  sleep_hours:
    column: duration_min
    transform: minutes_to_hours
    forecast_horizon: 7
    backtest_window: 30

models:
  sarimax:
    order: [1, 0, 0]
    seasonal_order: [0, 1, 1, 7]
  prophet:
    seasonality_mode: additive
  gbm:
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 100
  tft:
    enabled: false

reporting:
  output_dir: analysis_output/model_reports
