name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]' dvc
      - name: Lint
        run: ruff check .
      - name: Run tests
        run: pytest -q
      - name: Run sample pipeline
        run: |
          python -m sleep_analysis.cli ingest --source oura --path data/raw/vendor_samples/oura.csv --out data/processed/parquet
          python -m sleep_analysis.cli build-features --parquet-dir data/processed/parquet \
            --hrv data/raw/signals/hrv_sample.csv \
            --steps data/raw/signals/steps_sample.csv \
            --tags data/raw/signals/tags_sample.csv \
            --screen-time data/raw/signals/screen_time_sample.csv \
            --out data/processed/features
          python -m sleep_analysis.cli train --config configs/analytics_v2.yaml
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: model-reports-${{ matrix.python-version }}
          path: analysis_output/model_reports/
          if-no-files-found: ignore
